// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Categories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryDescription = "...",
                            CategoryName = "Beverages",
                            ImagePath = "beverages"
                        },
                        new
                        {
                            ID = 2,
                            CategoryDescription = "...",
                            CategoryName = "Breakfast Foods",
                            ImagePath = "breakfastfoods"
                        },
                        new
                        {
                            ID = 3,
                            CategoryDescription = "...",
                            CategoryName = "Dairy Products",
                            ImagePath = "dairyproducts"
                        },
                        new
                        {
                            ID = 4,
                            CategoryDescription = "...",
                            CategoryName = "Desserts",
                            ImagePath = "desserts"
                        },
                        new
                        {
                            ID = 5,
                            CategoryDescription = "...",
                            CategoryName = "Fast Foods",
                            ImagePath = "fastfoods"
                        },
                        new
                        {
                            ID = 6,
                            CategoryDescription = "...",
                            CategoryName = "Grain Foods",
                            ImagePath = "grainfoods"
                        },
                        new
                        {
                            ID = 7,
                            CategoryDescription = "...",
                            CategoryName = "Legume Dishes",
                            ImagePath = "legumedishes"
                        },
                        new
                        {
                            ID = 8,
                            CategoryDescription = "...",
                            CategoryName = "Main Courses",
                            ImagePath = "maincourses"
                        },
                        new
                        {
                            ID = 9,
                            CategoryDescription = "...",
                            CategoryName = "Meat Foods",
                            ImagePath = "meatfoods"
                        },
                        new
                        {
                            ID = 10,
                            CategoryDescription = "...",
                            CategoryName = "Nuts",
                            ImagePath = "nuts"
                        },
                        new
                        {
                            ID = 11,
                            CategoryDescription = "...",
                            CategoryName = "Pastry Foods",
                            ImagePath = "pastryfoods"
                        },
                        new
                        {
                            ID = 12,
                            CategoryDescription = "...",
                            CategoryName = "Salads",
                            ImagePath = "salads"
                        },
                        new
                        {
                            ID = 13,
                            CategoryDescription = "...",
                            CategoryName = "Sea Foods",
                            ImagePath = "seafoods"
                        },
                        new
                        {
                            ID = 14,
                            CategoryDescription = "...",
                            CategoryName = "Soups",
                            ImagePath = "soups"
                        },
                        new
                        {
                            ID = 15,
                            CategoryDescription = "...",
                            CategoryName = "Vegetable Foods",
                            ImagePath = "vegetablefoods"
                        },
                        new
                        {
                            ID = 16,
                            CategoryDescription = "...",
                            CategoryName = "Vegetables&fruits",
                            ImagePath = "vegetablesandfruits"
                        });
                });

            modelBuilder.Entity("Entities.CategoryDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasLactose")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllergen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegaterian")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID")
                        .IsUnique();

                    b.ToTable("Category Details", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            HasLactose = false,
                            IsAllergen = false,
                            IsGlutenFree = false,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 2,
                            HasLactose = true,
                            IsAllergen = true,
                            IsGlutenFree = false,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            HasLactose = true,
                            IsAllergen = true,
                            IsGlutenFree = false,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            HasLactose = true,
                            IsAllergen = false,
                            IsGlutenFree = false,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            HasLactose = false,
                            IsAllergen = false,
                            IsGlutenFree = true,
                            IsVegaterian = false
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 6,
                            HasLactose = false,
                            IsAllergen = true,
                            IsGlutenFree = true,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 7,
                            HasLactose = false,
                            IsAllergen = false,
                            IsGlutenFree = false,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 8,
                            HasLactose = false,
                            IsAllergen = false,
                            IsGlutenFree = false,
                            IsVegaterian = false
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 9,
                            HasLactose = false,
                            IsAllergen = false,
                            IsGlutenFree = false,
                            IsVegaterian = false
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 10,
                            HasLactose = false,
                            IsAllergen = true,
                            IsGlutenFree = false,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 11,
                            HasLactose = true,
                            IsAllergen = false,
                            IsGlutenFree = true,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 12,
                            HasLactose = false,
                            IsAllergen = false,
                            IsGlutenFree = false,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 13,
                            HasLactose = false,
                            IsAllergen = true,
                            IsGlutenFree = false,
                            IsVegaterian = false
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 14,
                            HasLactose = false,
                            IsAllergen = false,
                            IsGlutenFree = true,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 15,
                            HasLactose = false,
                            IsAllergen = false,
                            IsGlutenFree = false,
                            IsVegaterian = true
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 16,
                            HasLactose = false,
                            IsAllergen = false,
                            IsGlutenFree = false,
                            IsVegaterian = true
                        });
                });

            modelBuilder.Entity("Entities.Foods", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal");

                    b.Property<decimal>("CarbonHydrateValue")
                        .HasColumnType("decimal");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FatValue")
                        .HasColumnType("decimal");

                    b.Property<string>("FoodDescription")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FoodImagePath")
                        .HasColumnType("nvarchar");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("ProteinValue")
                        .HasColumnType("decimal");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Foods", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Calories = 37m,
                            CarbonHydrateValue = 2.7m,
                            CategoryID = 1,
                            FatValue = 2m,
                            FoodDescription = "1 glass is 200 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\beverages\\ayran.jpg",
                            FoodName = "Ayran",
                            ProteinValue = 2m
                        },
                        new
                        {
                            ID = 2,
                            Calories = 39m,
                            CarbonHydrateValue = 3.7m,
                            CategoryID = 1,
                            FatValue = 1.7m,
                            FoodDescription = "1 cup is 85 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\beverages\\cappucino.jpg",
                            FoodName = "Cappucino",
                            ProteinValue = 2.3m
                        },
                        new
                        {
                            ID = 3,
                            Calories = 61m,
                            CarbonHydrateValue = 10.9m,
                            CategoryID = 1,
                            FatValue = 0m,
                            FoodDescription = "1 glass is 200 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\beverages\\cola.jpg",
                            FoodName = "Cola",
                            ProteinValue = 0m
                        },
                        new
                        {
                            ID = 4,
                            Calories = 95m,
                            CarbonHydrateValue = 24m,
                            CategoryID = 1,
                            FatValue = 0m,
                            FoodDescription = "1 glass is 200 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\beverages\\soda.jpg",
                            FoodName = "Soda",
                            ProteinValue = 0m
                        },
                        new
                        {
                            ID = 5,
                            Calories = 158m,
                            CarbonHydrateValue = 0m,
                            CategoryID = 2,
                            FatValue = 11.2m,
                            FoodDescription = "1 piece is 60 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\breakfastfoods\\boiledegg.jpg",
                            FoodName = "Boiled Egg",
                            ProteinValue = 12.1m
                        },
                        new
                        {
                            ID = 6,
                            Calories = 315m,
                            CarbonHydrateValue = 78.4m,
                            CategoryID = 2,
                            FatValue = 0m,
                            FoodDescription = "1 teaspoon is 7 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\breakfastfoods\\honey.jpg",
                            FoodName = "Honey",
                            ProteinValue = 0.3m
                        },
                        new
                        {
                            ID = 7,
                            Calories = 207m,
                            CarbonHydrateValue = 2m,
                            CategoryID = 2,
                            FatValue = 2m,
                            FoodDescription = "1 piece is 4 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\breakfastfoods\\olive.jpg",
                            FoodName = "Olive",
                            ProteinValue = 1.8m
                        },
                        new
                        {
                            ID = 8,
                            Calories = 184m,
                            CarbonHydrateValue = 2.3m,
                            CategoryID = 2,
                            FatValue = 14.4m,
                            FoodDescription = "1 piece is 60 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\breakfastfoods\\omelette.jpg",
                            FoodName = "Omelette",
                            ProteinValue = 12.1m
                        },
                        new
                        {
                            ID = 9,
                            Calories = 215m,
                            CarbonHydrateValue = 81.1m,
                            CategoryID = 3,
                            FatValue = 0.1m,
                            FoodDescription = "1 teaspoon is 7 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\dairyproducts\\butter.jpg",
                            FoodName = "Butter",
                            ProteinValue = 0.9m
                        },
                        new
                        {
                            ID = 10,
                            Calories = 404m,
                            CarbonHydrateValue = 1.4m,
                            CategoryID = 3,
                            FatValue = 31.8m,
                            FoodDescription = "1 slice is 20 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\dairyproducts\\cheddarcheese.jpg",
                            FoodName = "Cheddar Cheese",
                            ProteinValue = 27m
                        },
                        new
                        {
                            ID = 11,
                            Calories = 289m,
                            CarbonHydrateValue = 0m,
                            CategoryID = 3,
                            FatValue = 21.6m,
                            FoodDescription = "1 cube is 30 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\dairyproducts\\fetacheese.jpg",
                            FoodName = "Feta Cheese",
                            ProteinValue = 22.5m
                        },
                        new
                        {
                            ID = 12,
                            Calories = 63m,
                            CarbonHydrateValue = 7m,
                            CategoryID = 3,
                            FatValue = 1.6m,
                            FoodDescription = "1 cup is 180 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\dairyproducts\\yogurt.jpg",
                            FoodName = "Yogurt",
                            ProteinValue = 5.3m
                        },
                        new
                        {
                            ID = 13,
                            Calories = 412m,
                            CarbonHydrateValue = 49.4m,
                            CategoryID = 4,
                            FatValue = 21.5m,
                            FoodDescription = "1 slice is 40 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\desserts\\baklava.jpg",
                            FoodName = "Baklava",
                            ProteinValue = 7.7m
                        },
                        new
                        {
                            ID = 14,
                            Calories = 331m,
                            CarbonHydrateValue = 36.3m,
                            CategoryID = 4,
                            FatValue = 19.1m,
                            FoodDescription = "1 slice is 125 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\desserts\\cheesecake.jpg",
                            FoodName = "Cheesecake",
                            ProteinValue = 4.8m
                        },
                        new
                        {
                            ID = 15,
                            Calories = 438m,
                            CarbonHydrateValue = 58.6m,
                            CategoryID = 4,
                            FatValue = 17.8m,
                            FoodDescription = "1 piece is 85 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\desserts\\donuts.jpg",
                            FoodName = "Donuts",
                            ProteinValue = 10m
                        },
                        new
                        {
                            ID = 16,
                            Calories = 360m,
                            CarbonHydrateValue = 38.1m,
                            CategoryID = 4,
                            FatValue = 18.7m,
                            FoodDescription = "1 piece is 95 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\desserts\\souffle.jpg",
                            FoodName = "Souffle",
                            ProteinValue = 7.3m
                        },
                        new
                        {
                            ID = 17,
                            Calories = 165m,
                            CarbonHydrateValue = 19.9m,
                            CategoryID = 5,
                            FatValue = 6.1m,
                            FoodDescription = "1 piece is 190 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\fastfoods\\hamburger.jpg",
                            FoodName = "Hamburger",
                            ProteinValue = 7m
                        },
                        new
                        {
                            ID = 18,
                            Calories = 253m,
                            CarbonHydrateValue = 28m,
                            CategoryID = 5,
                            FatValue = 11.9m,
                            FoodDescription = "1 piece is 175 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\fastfoods\\hotdog.jpg",
                            FoodName = "Hot Dog",
                            ProteinValue = 8.3m
                        },
                        new
                        {
                            ID = 19,
                            Calories = 94m,
                            CarbonHydrateValue = 2.3m,
                            CategoryID = 5,
                            FatValue = 2.4m,
                            FoodDescription = "1 half loaf is 245 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\fastfoods\\kokorec.jpg",
                            FoodName = "Kokorec",
                            ProteinValue = 15m
                        },
                        new
                        {
                            ID = 20,
                            Calories = 186m,
                            CarbonHydrateValue = 30.5m,
                            CategoryID = 5,
                            FatValue = 4.3m,
                            FoodDescription = "1 slice is 130 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\fastfoods\\pizza.jpg",
                            FoodName = "Pizza",
                            ProteinValue = 5.8m
                        },
                        new
                        {
                            ID = 21,
                            Calories = 114m,
                            CarbonHydrateValue = 18.2m,
                            CategoryID = 6,
                            FatValue = 3.4m,
                            FoodDescription = "1 portion is 130 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\grainfoods\\bulgurpilaf.jpg",
                            FoodName = "Bulgur Pilaf",
                            ProteinValue = 2.8m
                        },
                        new
                        {
                            ID = 22,
                            Calories = 357m,
                            CarbonHydrateValue = 84.1m,
                            CategoryID = 6,
                            FatValue = 0.4m,
                            FoodDescription = "1 case is 50 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\grainfoods\\cornflakes.jpg",
                            FoodName = "Corn Flakes",
                            ProteinValue = 7.5m
                        },
                        new
                        {
                            ID = 23,
                            Calories = 162m,
                            CarbonHydrateValue = 24.8m,
                            CategoryID = 6,
                            FatValue = 5.8m,
                            FoodDescription = "1 portion is 170 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\grainfoods\\rice.jpg",
                            FoodName = "Rice",
                            ProteinValue = 2.1m
                        },
                        new
                        {
                            ID = 24,
                            Calories = 77m,
                            CarbonHydrateValue = 11.7m,
                            CategoryID = 6,
                            FatValue = 1.8m,
                            FoodDescription = "1 portion is 130 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\grainfoods\\rolledoats.jpg",
                            FoodName = "Rolled Oats",
                            ProteinValue = 3.3m
                        },
                        new
                        {
                            ID = 25,
                            Calories = 27m,
                            CarbonHydrateValue = 3.3m,
                            CategoryID = 7,
                            FatValue = 0.3m,
                            FoodDescription = "1 portion is 130 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\legumedishes\\greenbeans.jpg",
                            FoodName = "Green Beans",
                            ProteinValue = 2.6m
                        },
                        new
                        {
                            ID = 26,
                            Calories = 84m,
                            CarbonHydrateValue = 14.4m,
                            CategoryID = 7,
                            FatValue = 0.4m,
                            FoodDescription = "1 portion is 180 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\legumedishes\\greenpea.jpg",
                            FoodName = "Green Pea",
                            ProteinValue = 6.3m
                        },
                        new
                        {
                            ID = 27,
                            Calories = 281m,
                            CarbonHydrateValue = 29.4m,
                            CategoryID = 7,
                            FatValue = 1.4m,
                            FoodDescription = "1 portion is 250 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\legumedishes\\haricotbean.jpg",
                            FoodName = "Haricot Bean",
                            ProteinValue = 21.8m
                        },
                        new
                        {
                            ID = 28,
                            Calories = 340m,
                            CarbonHydrateValue = 60.1m,
                            CategoryID = 7,
                            FatValue = 1.1m,
                            FoodDescription = "1 portion is 230 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\legumedishes\\lentildish.jpg",
                            FoodName = "Lentil Dish",
                            ProteinValue = 24.7m
                        },
                        new
                        {
                            ID = 29,
                            Calories = 104m,
                            CarbonHydrateValue = 2.8m,
                            CategoryID = 8,
                            FatValue = 8m,
                            FoodDescription = "1 portion is 416 g",
                            FoodImagePath = "..\\..\\..\\Image\\Images\\maincourses\\alinazik.jpg",
                            FoodName = "Alinazik",
                            ProteinValue = 5.2m
                        },
                        new
                        {
                            ID = 30,
                            Calories = 152m,
                            CarbonHydrateValue = 3.5m,
                            CategoryID = 8,
                            FatValue = 9.2m,
                            FoodDescription = "1 portion is 266 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\maincourses\\beefstroganoff.jpg",
                            FoodName = "Beef Stroganoff",
                            ProteinValue = 13.4m
                        },
                        new
                        {
                            ID = 31,
                            Calories = 198m,
                            CarbonHydrateValue = 26.5m,
                            CategoryID = 8,
                            FatValue = 10.2m,
                            FoodDescription = "1 portion is 195 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\maincourses\\biryani.jpg",
                            FoodName = "Biryani",
                            ProteinValue = 2.3m
                        },
                        new
                        {
                            ID = 32,
                            Calories = 151m,
                            CarbonHydrateValue = 15.5m,
                            CategoryID = 8,
                            FatValue = 5.4m,
                            FoodDescription = "1 portion is 500 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\maincourses\\iskender.jpg",
                            FoodName = "İskender",
                            ProteinValue = 9.7m
                        },
                        new
                        {
                            ID = 33,
                            Calories = 183m,
                            CarbonHydrateValue = 5.6m,
                            CategoryID = 9,
                            FatValue = 11.6m,
                            FoodDescription = "1 portion is 150 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\meatfoods\\beef.jpg",
                            FoodName = "Beef",
                            ProteinValue = 13.4m
                        },
                        new
                        {
                            ID = 34,
                            Calories = 215m,
                            CarbonHydrateValue = 0m,
                            CategoryID = 9,
                            FatValue = 15.1m,
                            FoodDescription = "1 portion is 170 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\meatfoods\\chicken.jpg",
                            FoodName = "Chicken",
                            ProteinValue = 18.6m
                        },
                        new
                        {
                            ID = 35,
                            Calories = 345m,
                            CarbonHydrateValue = 0m,
                            CategoryID = 9,
                            FatValue = 28.5m,
                            FoodDescription = "1 portion is 360 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\meatfoods\\kavurma.jpg",
                            FoodName = "Kavurma",
                            ProteinValue = 20.6m
                        },
                        new
                        {
                            ID = 36,
                            Calories = 137m,
                            CarbonHydrateValue = 2.6m,
                            CategoryID = 9,
                            FatValue = 7.6m,
                            FoodDescription = "1 portion is 237 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\meatfoods\\kusbasi.jpg",
                            FoodName = "Kuşbaşı",
                            ProteinValue = 5.8m
                        },
                        new
                        {
                            ID = 37,
                            Calories = 600m,
                            CarbonHydrateValue = 19.8m,
                            CategoryID = 10,
                            FatValue = 54.2m,
                            FoodDescription = "1 piece is 2 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\nuts\\almond.jpg",
                            FoodName = "Almond",
                            ProteinValue = 18.6m
                        },
                        new
                        {
                            ID = 38,
                            Calories = 574m,
                            CarbonHydrateValue = 32.7m,
                            CategoryID = 10,
                            FatValue = 46.4m,
                            FoodDescription = "1 piece is 4 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\nuts\\cashew.jpg",
                            FoodName = "Cashew",
                            ProteinValue = 11.3m
                        },
                        new
                        {
                            ID = 39,
                            Calories = 634m,
                            CarbonHydrateValue = 16.8m,
                            CategoryID = 10,
                            FatValue = 62.4m,
                            FoodDescription = "1 piece is 2 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\nuts\\hazelnut.jpg",
                            FoodName = "Hazelnut",
                            ProteinValue = 12.6m
                        },
                        new
                        {
                            ID = 40,
                            Calories = 610m,
                            CarbonHydrateValue = 10m,
                            CategoryID = 10,
                            FatValue = 50m,
                            FoodDescription = "1 handful is 10 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\nuts\\pumpkinseeds.jpg",
                            FoodName = "Pumpkin Seeds",
                            ProteinValue = 30.1m
                        },
                        new
                        {
                            ID = 41,
                            Calories = 259m,
                            CarbonHydrateValue = 33.5m,
                            CategoryID = 11,
                            FatValue = 9.14m,
                            FoodDescription = "1 portion is 150 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\pastryfoods\\borek.jpg",
                            FoodName = "Börek",
                            ProteinValue = 10.1m
                        },
                        new
                        {
                            ID = 42,
                            Calories = 256m,
                            CarbonHydrateValue = 52.8m,
                            CategoryID = 11,
                            FatValue = 0.9m,
                            FoodDescription = "1 piece is 25 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\pastryfoods\\bread.jpg",
                            FoodName = "Bread",
                            ProteinValue = 8.1m
                        },
                        new
                        {
                            ID = 43,
                            Calories = 271m,
                            CarbonHydrateValue = 42m,
                            CategoryID = 11,
                            FatValue = 7.4m,
                            FoodDescription = "1 piece is 60 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\pastryfoods\\croissant.jpg",
                            FoodName = "Croissant",
                            ProteinValue = 8.2m
                        },
                        new
                        {
                            ID = 44,
                            Calories = 255m,
                            CarbonHydrateValue = 48.9m,
                            CategoryID = 11,
                            FatValue = 5.2m,
                            FoodDescription = "1 piece is 100 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\pastryfoods\\simit.jpg",
                            FoodName = "Simit",
                            ProteinValue = 2.3m
                        },
                        new
                        {
                            ID = 45,
                            Calories = 128m,
                            CarbonHydrateValue = 6.6m,
                            CategoryID = 12,
                            FatValue = 5m,
                            FoodDescription = "1 portion is 365 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\salads\\ceasarsalad.jpg",
                            FoodName = "Ceasar Salad",
                            ProteinValue = 23.8m
                        },
                        new
                        {
                            ID = 46,
                            Calories = 52m,
                            CarbonHydrateValue = 7.6m,
                            CategoryID = 12,
                            FatValue = 1.7m,
                            FoodDescription = "1 portion is 220 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\salads\\cobansalad.jpg",
                            FoodName = "Çoban Salad",
                            ProteinValue = 1.5m
                        },
                        new
                        {
                            ID = 47,
                            Calories = 188m,
                            CarbonHydrateValue = 2m,
                            CategoryID = 12,
                            FatValue = 13.8m,
                            FoodDescription = "1 portion is 173 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\salads\\cobbsalad.jpg",
                            FoodName = "Cobb Salad",
                            ProteinValue = 13.9m
                        },
                        new
                        {
                            ID = 48,
                            Calories = 73m,
                            CarbonHydrateValue = 5m,
                            CategoryID = 12,
                            FatValue = 5m,
                            FoodDescription = "1 portion is 155 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\salads\\gavurdagisalad.jpg",
                            FoodName = "Gavurdağı Salad",
                            ProteinValue = 1.9m
                        },
                        new
                        {
                            ID = 49,
                            Calories = 115m,
                            CarbonHydrateValue = 0m,
                            CategoryID = 13,
                            FatValue = 5m,
                            FoodDescription = "1 portion is 200 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\seafoods\\anchovy.jpg",
                            FoodName = "Anchovy",
                            ProteinValue = 17m
                        },
                        new
                        {
                            ID = 50,
                            Calories = 85m,
                            CarbonHydrateValue = 0m,
                            CategoryID = 13,
                            FatValue = 0.5m,
                            FoodDescription = "1 portion is 100 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\seafoods\\prawn.jpg",
                            FoodName = "Prawn",
                            ProteinValue = 20.1m
                        },
                        new
                        {
                            ID = 51,
                            Calories = 179m,
                            CarbonHydrateValue = 0m,
                            CategoryID = 13,
                            FatValue = 10.4m,
                            FoodDescription = "1 portion is 150 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\seafoods\\salmon.jpg",
                            FoodName = "Salmon",
                            ProteinValue = 19.9m
                        },
                        new
                        {
                            ID = 52,
                            Calories = 113m,
                            CarbonHydrateValue = 7m,
                            CategoryID = 13,
                            FatValue = 6.7m,
                            FoodDescription = "1 portion is 170 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\seafoods\\sushi.jpg",
                            FoodName = "Sushi",
                            ProteinValue = 7.3m
                        },
                        new
                        {
                            ID = 53,
                            Calories = 45m,
                            CarbonHydrateValue = 5.9m,
                            CategoryID = 14,
                            FatValue = 1.2m,
                            FoodDescription = "1 ladle is 150 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\soups\\ezogelinsoup.jpg",
                            FoodName = "Ezogelin Soup",
                            ProteinValue = 1.9m
                        },
                        new
                        {
                            ID = 54,
                            Calories = 49m,
                            CarbonHydrateValue = 4.4m,
                            CategoryID = 14,
                            FatValue = 1.3m,
                            FoodDescription = "1 ladle is 150 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\soups\\fishsoup.jpg",
                            FoodName = "Fish Soup",
                            ProteinValue = 4.5m
                        },
                        new
                        {
                            ID = 55,
                            Calories = 46m,
                            CarbonHydrateValue = 8.3m,
                            CategoryID = 14,
                            FatValue = 0.2m,
                            FoodDescription = "1 ladle is 150 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\soups\\lentilsoup.jpg",
                            FoodName = "Lentil Soup",
                            ProteinValue = 2.5m
                        },
                        new
                        {
                            ID = 56,
                            Calories = 32m,
                            CarbonHydrateValue = 4.4m,
                            CategoryID = 14,
                            FatValue = 1.1m,
                            FoodDescription = "1 ladle is 150 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\soups\\tomatosoup.jpg",
                            FoodName = "Tomato Soup",
                            ProteinValue = 0.9m
                        },
                        new
                        {
                            ID = 57,
                            Calories = 53m,
                            CarbonHydrateValue = 12m,
                            CategoryID = 15,
                            FatValue = 0.3m,
                            FoodDescription = "1 portion is 100 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\vegetablefoods\\artichoke.jpg",
                            FoodName = "Artichoke",
                            ProteinValue = 2.9m
                        },
                        new
                        {
                            ID = 58,
                            Calories = 83m,
                            CarbonHydrateValue = 83m,
                            CategoryID = 15,
                            FatValue = 5m,
                            FoodDescription = "1 piece is 60 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\vegetablefoods\\mucver.jpg",
                            FoodName = "Mücver",
                            ProteinValue = 3.7m
                        },
                        new
                        {
                            ID = 59,
                            Calories = 27m,
                            CarbonHydrateValue = 4.4m,
                            CategoryID = 15,
                            FatValue = 0.7m,
                            FoodDescription = "1 portion is 480 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\vegetablefoods\\ratatouille.jpg",
                            FoodName = "Ratatouille",
                            ProteinValue = 1.1m
                        },
                        new
                        {
                            ID = 60,
                            Calories = 76m,
                            CarbonHydrateValue = 5.7m,
                            CategoryID = 15,
                            FatValue = 4.6m,
                            FoodDescription = "1 portion is 175 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\vegetablefoods\\spinachmeal.jpg",
                            FoodName = "Spinach Meal",
                            ProteinValue = 2.6m
                        },
                        new
                        {
                            ID = 61,
                            Calories = 58m,
                            CarbonHydrateValue = 15m,
                            CategoryID = 16,
                            FatValue = 0.6m,
                            FoodDescription = "1 piece is 90 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\vegetablesandfruits\\apple.jpg",
                            FoodName = "Apple",
                            ProteinValue = 0.2m
                        },
                        new
                        {
                            ID = 62,
                            Calories = 160m,
                            CarbonHydrateValue = 8.5m,
                            CategoryID = 16,
                            FatValue = 14.7m,
                            FoodDescription = "1 piece is 140 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\vegetablesandfruits\\avocado.jpg",
                            FoodName = "Avocado",
                            ProteinValue = 2m
                        },
                        new
                        {
                            ID = 63,
                            Calories = 85m,
                            CarbonHydrateValue = 11.6m,
                            CategoryID = 16,
                            FatValue = 0.2m,
                            FoodDescription = "1 piece is 170 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\vegetablesandfruits\\banana.jpg",
                            FoodName = "Banana",
                            ProteinValue = 1.1m
                        },
                        new
                        {
                            ID = 64,
                            Calories = 10m,
                            CarbonHydrateValue = 10m,
                            CategoryID = 16,
                            FatValue = 0.2m,
                            FoodDescription = "1 piece is 40 g",
                            FoodImagePath = "..\\..\\..\\Resources\\Images\\vegetablesandfruits\\carrot.jpg",
                            FoodName = "Carrot",
                            ProteinValue = 0.1m
                        });
                });

            modelBuilder.Entity("Entities.Meal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Meals", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MealName = "Breakfast"
                        },
                        new
                        {
                            ID = 2,
                            MealName = "Lunch"
                        },
                        new
                        {
                            ID = 3,
                            MealName = "Dinner"
                        },
                        new
                        {
                            ID = 4,
                            MealName = "Snack"
                        });
                });

            modelBuilder.Entity("Entities.User_Food_Meal", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("MealID")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MealDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID", "FoodID", "MealID");

                    b.HasIndex("FoodID");

                    b.HasIndex("MealID");

                    b.ToTable("User Food Meals", (string)null);
                });

            modelBuilder.Entity("Entities.UserDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("GlutenPreference")
                        .HasColumnType("bit");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllergic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLactoseIntolerant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("User Details", (string)null);
                });

            modelBuilder.Entity("Entities.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "overthinkersapp@gmail.com",
                            FirstName = "admin",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "admin",
                            Password = "60fe74406e7f353ed979f350f2fbb6a2e8690a5fa7d1b0c32983d1d8b3f95f67"
                        });
                });

            modelBuilder.Entity("Entities.CategoryDetails", b =>
                {
                    b.HasOne("Entities.Categories", "Categories")
                        .WithOne("CategoryDetails")
                        .HasForeignKey("Entities.CategoryDetails", "CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Entities.Foods", b =>
                {
                    b.HasOne("Entities.Categories", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.User_Food_Meal", b =>
                {
                    b.HasOne("Entities.Foods", "Foods")
                        .WithMany("UsersMeals")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Meal", "Meals")
                        .WithMany("UsersMeals")
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Users", "Users")
                        .WithMany("UsersMeals")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foods");

                    b.Navigation("Meals");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entities.UserDetails", b =>
                {
                    b.HasOne("Entities.Users", "Users")
                        .WithOne("UserDetails")
                        .HasForeignKey("Entities.UserDetails", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entities.Categories", b =>
                {
                    b.Navigation("CategoryDetails");

                    b.Navigation("Foods");
                });

            modelBuilder.Entity("Entities.Foods", b =>
                {
                    b.Navigation("UsersMeals");
                });

            modelBuilder.Entity("Entities.Meal", b =>
                {
                    b.Navigation("UsersMeals");
                });

            modelBuilder.Entity("Entities.Users", b =>
                {
                    b.Navigation("UserDetails");

                    b.Navigation("UsersMeals");
                });
#pragma warning restore 612, 618
        }
    }
}
